# r4ds

Misc Notes from r4ds: https://r4ds.hadley.nz/

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggthemes)

glimpse(penguins)
```


```{r}

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
  ) +
  geom_point(mapping = aes(color = species, shape = species), na.rm = T) +
  geom_smooth(method = "lm") +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", y = "Body mass (g)",
    color = "Species", shape = "Species",
    caption = "Antidisestablishmentarianism"
  ) +
  scale_color_colorblind()

```

```{r}
# exercises 1.2.5

# 1
str(penguins)

# 2

# 3
penguins %>%
  ggplot(aes(bill_depth_mm, bill_length_mm, color = species)) +
  geom_point(na.rm = T)

# 8

ggplot(
  data = penguins,
  aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(aes(color = bill_depth_mm)) + 
  geom_smooth()

# 9
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = island)
) +
  geom_point() +
  geom_smooth(se = FALSE)
```


```{r eval = F}
# 1.4.3

ggplot(penguins, aes(x = species)) +
  geom_bar(color = "red")

ggplot(penguins, aes(x = species)) +
  geom_bar(fill = "red")

diamonds |>
  ggplot(aes(x = carat)) +
  geom_histogram(binwidth = .05)

ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() +
  labs(color = "Species",
       shape = "Species")

```

```{r eval = F}
# ctrl + shift + m shortcut for |> 

# 3.5.7
library(nycflights13)

# 1
flights |> 
  group_by(carrier) |> 
  summarise(mean_delay = mean(arr_delay, na.rm = T)) %>%
  arrange(desc(mean_delay))

# 2
flights |> 
  group_by(carrier, dest) |> 
  summarise(n()) %>%
```


```{r}
df <- tibble(
  x = 1:5,
  y = c("a", "b", "a", "a", "b"),
  z = c("K", "K", "L", "L", "K")
)

df |>
  group_by(y) |>
  summarize(mean_x = mean(x))

df |>
  group_by(y, z) |>
  summarize(mean_x = mean(x))

df |>
  group_by(y, z) |>
  summarize(mean_x = mean(x), .groups = "drop")
```

```{r eval = F}

con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "duckdb")

dbWriteTable(con, "mpg", ggplot2::mpg)
dbWriteTable(con, "diamonds", ggplot2::diamonds)

```

